# Sıfırdan Yapay Sinir Ağı Yazma
![alt text](https://i.hizliresim.com/r0dkq7.jpg)

Şekilde görülen yapay sinir ağı (neural network) için ileri yönlü hesaplamayı Python'da yapınız.

Mavi ile gösterilen nöronlarda aktivasyon fonksiyonu uygulamayı unutmayınız. Aktivasyon fonksiyonu olarak sigmoid kullanınız.
Sizden istenenler:

Verilen giriş, ağırlık ve bias değerlerine göre ileri yönlü hesaplamayı yapabilen Python programını yazmak.
o1 ve o2 nöronlarının çıktılarını hesaplamak.

In [0]:
import numpy as np

In [0]:

i1, i2 = 0.05, 0.10
w1, w2, w3, w4 = 0.15, 0.20, 0.25, 0.30
b1, b2 = 0.35, 0.60
w5, w6, w7, w8 = 0.40, 0.45, 0.50, 0.55
n=0.5

In [0]:
def sigmoid (x):
  return 1/(1+np.exp(-x))
  

In [8]:
training_inputs_1 = np.array([i1,i2])
training_inputs_1.resize(1,2)
print(training_inputs_1)

[[0.05 0.1 ]]


In [9]:
weights_1 = np.array([w1,w2])
weights_1.resize(2,1)
print(weights_1)
h1 = float(sigmoid(np.dot(training_inputs_1,weights_1) + b1))
print("h1:",h1)

[[0.15]
 [0.2 ]]
h1: 0.5932699921071872


In [10]:
weights_2= np.array([w3,w4])
weights_2.resize(2,1)
print(weights_2)
h2 = float(sigmoid(np.dot(training_inputs_1,weights_2) + b1))
print("h2:", h2)

[[0.25]
 [0.3 ]]
h2: 0.596884378259767


In [11]:
training_inputs_2 = np.array([h1,h2])
training_inputs_2.resize(1,2)
print(training_inputs_2)

[[0.59326999 0.59688438]]


In [12]:
weights_3= np.array([w5,w6])
weights_3.resize(2,1)
print(weights_3)
o1 = float(sigmoid(np.dot(training_inputs_2,weights_3) + b2))
print("o1:",o1)

[[0.4 ]
 [0.45]]
o1: 0.7513650695523157


In [13]:
weights_4 = np.array([w7,w8])
weights_4.resize(2,1)
print(weights_4)
o2 = float(sigmoid(np.dot(training_inputs_2, weights_4) + b2))
print("o2:",o2)

[[0.5 ]
 [0.55]]
o2: 0.7729284653214625


In [14]:
output_inputs = np.array([o1,o2])
output_inputs.resize(1,2)
print(output_inputs)

[[0.75136507 0.77292847]]
